---
abstract: 'A module that ...'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  Test::Fake::HTTPD: 0.03
  Test::More: 0.98
  Test::UseAllModules: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mock-LWP-Conditional
no_index:
  directory:
    - inc
provides:
  Test::Mock::LWP::Conditional:
    file: lib/Test/Mock/LWP/Conditional.pm
    version: 0.02
  Test::Mock::LWP::Conditional::Stubs:
    file: lib/Test/Mock/LWP/Conditional/Stubs.pm
    version: 0
requires:
  Class::Method::Modifiers: 0
  LWP::UserAgent: 0
  Scalar::Util: 1.14
  Sub::Install: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/Test-Mock-LWP-Conditional.git
version: 0.02
